services:
  gluetun:
    image: qmcgaw/gluetun:v3
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - "7000:7000"
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
      - WIREGUARD_ENDPOINT_IP=${WIREGUARD_ENDPOINT_IP}
      - WIREGUARD_ENDPOINT_PORT=${WIREGUARD_ENDPOINT_PORT}
      - WIREGUARD_PUBLIC_KEY=${WIREGUARD_PUBLIC_KEY}
    restart: unless-stopped

  frontend:
    image: xdillfrescott/bitlab:latest
    container_name: bitmagnet-stremio-frontend
    restart: unless-stopped
    network_mode: "service:gluetun"
    environment:
      - PORT=7000
      - TIMEZONE=America/New_York
      - BASE_URL=https://bitlab.dill.moe
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - SESSION_SECRET=${SESSION_SECRET}
      - BITMAGNET_URL=http://localhost:3333
      - BITMAGNET_WEBUI_URL=https://bitlab.dill.moe/admin/bitmagnet/
      - TORRENT_CACHE_RESERVE_GB=10
      - TORRENT_IDLE_GRACE_MS=120000
      - TORRENT_SWEEP_INTERVAL_MS=30000
      - METADATA_TIMEOUT_MS=90000
      - TORRENT_TRACKER_LIST_URL=https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_best.txt
      - TORRENT_TRACKER_REFRESH_MS=21600000
      - TORRENT_MAX_CONNS=500
    volumes:
      - ./data/frontend:/app/data
      - ./cache:/tmp/webtorrent
    depends_on:
      gluetun:
        condition: service_healthy

  bitmagnet:
    image: ghcr.io/bitmagnet-io/bitmagnet:latest
    container_name: bitmagnet
    restart: unless-stopped
    network_mode: "service:gluetun"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - TMDB_API_KEY=${TMDB_API_KEY}
      - PROCESSOR_CONCURRENCY=4
      - DHT_CRAWLER_SCALING_FACTOR=4
    volumes:
      - ./config/bitmagnet:/root/.config/bitmagnet
    command:
      - worker
      - run
      - --keys=http_server
      - --keys=queue_server
      - --keys=dht_crawler
    depends_on:
      gluetun:
        condition: service_healthy
      postgres:
        condition: service_healthy


  postgres:
    image: postgres:18-alpine
    container_name: bitmagnet-postgres
    volumes:
      - /mnt/drive/postgres:/var/lib/postgresql
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=bitmagnet
      - PGUSER=postgres
    shm_size: 1g
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready
      start_period: 20s
      interval: 10s
